services:
  bot:
    build: .
    container_name: capybot
    restart: always
    env_file:
      - .env
    volumes:
      - ./temp:/usr/src/app/temp
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
